---
title: "Mini-Project 2"
author: "Ellen Dong and Christina Hung"
date: "2019-03-24"
output: 
  html_document:
    code_folding: hide
---


## Loading the data

This project is so interesting and relevant to my life!

```{r, message = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```
## Some basic EDA


- How many candidates running for what offices?

```{r}
candidates %>%
  group_by(cand_election_yr, cand_office, cand_office_state) %>%
  summarize(num_candidates = n()) %>%
  print(n = Inf)
```

Note that this appears to be cumulative!

- How many committees [by type](https://classic.fec.gov/finance/disclosure/metadata/CommitteeTypeCodes.shtml)?

```{r}
committees %>%
  group_by(cmte_type) %>%
  summarize(num_committees = n(), 
            cand_ids = sum(cand_id > "")) %>%
  arrange(desc(num_committees))
```

- What types of contributions are there and where do they go?

```{r}
contributions %>%
  group_by(entity_type) %>%
  summarize(num_contributions = n(), 
            total_amount = sum(transaction_amt), 
            other_ids = sum(other_id > ""),
            cand_ids = sum(cand_id > "")) %>%
  arrange(desc(num_contributions))
```



our code

```{r}
## Filtering and Grouping the Contributions and House Elections Tables
ca_house_elections <- house_elections %>%
  filter(state == "CA") %>%
  group_by(district)

ca_contributions <- contributions %>%
  filter(state == "CA") %>%
  group_by(transaction_amt)
```

```{r} 
## Joining the Contributions and House Elections Tables
contributions_helections <- ca_house_elections %>% 
  inner_join(ca_house_elections, ca_contributions, by = "state")
```

```{r}
## Selecting Columns from the Joined Table
contributions_helections <-contributions_helections %>%
  select(candidate_name.x, incumbent.x, primary_votes.x) %>%
  #filter(incumbent.x == "TRUE") %>%
  mutate(mean_votes = mean(primary_votes.x, na.rm = TRUE))

View(contributions_helections)
```

```{r eval = FALSE}
## Make a Plot
ggplot(contributions_helections, aes(x = district.x, y = mean_votes, color = district.x)) + 
  geom_point() 
```


```{r}
ggplot(contributions_helections, aes(x = district.x, y = mean_votes)) + 
  geom_point(aes(color = incumbent.x))
```






